version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.3.1
    container_name: localstack-meowtest
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda, s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
